version: "3.3"
services:
  angular-app:
    container_name: angular-app
    restart: always
    build:
      context: ./angular-app
    environment:
      - API_URL=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
    ports:
      - "80:80"
  node-app:
    container_name: node-app
    restart: always
    build:
      context: ./node-app
    environment:
      - ANGULAR_HOST=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"